try {
  console.log(a);
} catch {
  console.log("Catch Block");
}
